export const UPDATE_SELECTED_ROUTES = 'UPDATE_SELECTED_ROUTES';
export type UPDATE_SELECTED_ROUTES = typeof UPDATE_SELECTED_ROUTES;

export const UPDATE_LAST_TIME = 'UPDATE_LAST_TIME';
export type UPDATE_LAST_TIME = typeof UPDATE_LAST_TIME;

export const UPDATE_LOCATIONS = 'UPDATE_LOCATIONS';
export type UPDATE_LOCATIONS = typeof UPDATE_LOCATIONS;