export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const UPDATE_LAST_TIME = 'UPDATE_LAST_TIME';
export type UPDATE_LAST_TIME = typeof UPDATE_LAST_TIME;

export const UPDATE_LOCATIONS = 'UPDATE_LOCATIONS';
export type UPDATE_LOCATIONS = typeof UPDATE_LOCATIONS;